{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "SUPER,Return,exec,uwsm app -- wezterm"
      "SUPER,Return,global,caelestia:launcher"
      #----------MOD---------------------------------------->>
      "SUPER,B,exec,uwsm app -- brave"
      "SUPER,C,exec,hyprpicker -a"
      "SUPER,F,fullscreen,"
      "SUPER,P,exec,uwsm app -- plex-desktop"
      "SUPER,Q,killactive,"
      "SUPER,S,exec,uwsm app -- signal-desktop"
      "SUPER,T,exec,uwsm app -- thunar"
      "SUPER,W,exec,uwsm app -- wezterm"
      "SUPER,Y,exec,uwsm app -- kitty -e yazi"
      #----------MOD-SHIFT---------------------------------->>
      "SUPER,C,exit,"
      "SUPER,F,togglefloating,"
      "SUPER,I,togglesplit,"
      "SUPER,K,exec,uwsm app -- kitty"
      "SUPER,M,exec,uwsm app -- mullvad-vpn"
      "SUPER,P,exec,uwsm app -- plexamp"
      "SUPER,left,movewindow,l"
      "SUPER,right,movewindow,r"
      "SUPER,up,movewindow,u"
      "SUPER,down,movewindow,d"
      "SUPER,h,movewindow,l"
      "SUPER,l,movewindow,r"
      "SUPER,k,movewindow,u"
      "SUPER,j,movewindow,d"
      #----------MOD-ALT------------------------------------>>
      "SUPER,D,exec,pseudo" # Dwindle
      "SUPER,P,exec,pwvucontrol"
      "SUPER,F,workspaceopt, allfloat"
      "SUPER, left, swapwindow,l"
      "SUPER, right, swapwindow,r"
      "SUPER, up, swapwindow,u"
      "SUPER, down, swapwindow,d"
      "SUPER, 43, swapwindow,l"
      "SUPER, 46, swapwindow,r"
      "SUPER, 45, swapwindow,u"
      "SUPER, 44, swapwindow,d"
      #----------WORKSPACES--------------------------------->>
      "SUPER,left,movefocus,l"
      "SUPER,right,movefocus,r"
      "SUPER,up,movefocus,u"
      "SUPER,down,movefocus,d"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPER,1,workspace,1"
      "SUPER,2,workspace,2"
      "SUPER,3,workspace,3"
      "SUPER,4,workspace,4"
      "SUPER,5,workspace,5"
      "SUPER,6,workspace,6"
      "SUPER,7,workspace,7"
      "SUPER,8,workspace,8"
      "SUPER,9,workspace,9"
      "SUPER,0,workspace,10"
      "SUPER,SPACE,movetoworkspace,special"
      "SUPER,SPACE,togglespecialworkspace"
      "SUPER,1,movetoworkspace,1"
      "SUPER,2,movetoworkspace,2"
      "SUPER,3,movetoworkspace,3"
      "SUPER,4,movetoworkspace,4"
      "SUPER,5,movetoworkspace,5"
      "SUPER,6,movetoworkspace,6"
      "SUPER,7,movetoworkspace,7"
      "SUPER,8,movetoworkspace,8"
      "SUPER,9,movetoworkspace,9"
      "SUPER,0,movetoworkspace,10"
      "SUPER,right,workspace,e+1"
      "SUPER,left,workspace,e-1"
      "SUPER,mouse_down,workspace, e+1"
      "SUPER,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      "ALT,space,exec,global,caelestia:launcher"
      #----------AUDIO----------------------------------->>
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "SUPER, mouse:272, movewindow"
      "SUPER, mouse:273, resizewindow"
    ];
  };
}
