{
  wayland.windowManager.hyprland.settings = {
    "$mainMod" = "SUPER";
    bind = [
      "$mainMod,Return,exec,uwsm app -- wezterm"
      "$mainMod SHIFT,Return,global,caelestia:launcher"
      #----------MOD---------------------------------------->>
      "$mainMod,B,exec,uwsm app -- brave"
      "$mainMod,C,exec,hyprpicker -a"
      "$mainMod,D,exec,uwsm app -- discord"
      "$mainMod,F,fullscreen,"
      "$mainMod,P,exec,uwsm app -- plex-desktop"
      "$mainMod,Q,killactive,"
      "$mainMod,S,exec,uwsm app -- signal-desktop"
      "$mainMod,T,exec,uwsm app -- thunar"
      "$mainMod,W,exec,uwsm app -- wezterm"
      "$mainMod,Y,exec,uwsm app -- kitty -e yazi"
      #----------MOD-SHIFT---------------------------------->>
      "$mainMod SHIFT,C,exit,"
      "$mainMod SHIFT,F,togglefloating,"
      "$mainMod SHIFT,I,togglesplit,"
      "$mainMod SHIFT,K,exec,uwsm app -- kitty"
      "$mainMod SHIFT,M,exec,uwsm app -- mullvad-vpn"
      "$mainMod SHIFT,P,exec,uwsm app -- plexamp"
      "$mainMod SHIFT,left,movewindow,l"
      "$mainMod SHIFT,right,movewindow,r"
      "$mainMod SHIFT,up,movewindow,u"
      "$mainMod SHIFT,down,movewindow,d"
      "$mainMod SHIFT,h,movewindow,l"
      "$mainMod SHIFT,l,movewindow,r"
      "$mainMod SHIFT,k,movewindow,u"
      "$mainMod SHIFT,j,movewindow,d"
      #----------MOD-ALT------------------------------------>>
      "$mainMod ALT,D,exec,pseudo" # Dwindle
      "$mainMod ALT,P,exec,pwvucontrol"
      "$mainMod ALT,F,workspaceopt, allfloat"
      "$mainMod ALT, left, swapwindow,l"
      "$mainMod ALT, right, swapwindow,r"
      "$mainMod ALT, up, swapwindow,u"
      "$mainMod ALT, down, swapwindow,d"
      "$mainMod ALT, 43, swapwindow,l"
      "$mainMod ALT, 46, swapwindow,r"
      "$mainMod ALT, 45, swapwindow,u"
      "$mainMod ALT, 44, swapwindow,d"
      #----------WORKSPACES--------------------------------->>
      "$mainMod,left,movefocus,l"
      "$mainMod,right,movefocus,r"
      "$mainMod,up,movefocus,u"
      "$mainMod,down,movefocus,d"
      "$mainMod,h,movefocus,l"
      "$mainMod,l,movefocus,r"
      "$mainMod,k,movefocus,u"
      "$mainMod,j,movefocus,d"
      "$mainMod,1,workspace,1"
      "$mainMod,2,workspace,2"
      "$mainMod,3,workspace,3"
      "$mainMod,4,workspace,4"
      "$mainMod,5,workspace,5"
      "$mainMod,6,workspace,6"
      "$mainMod,7,workspace,7"
      "$mainMod,8,workspace,8"
      "$mainMod,9,workspace,9"
      "$mainMod,0,workspace,10"
      "$mainMod SHIFT,SPACE,movetoworkspace,special"
      "$mainMod,SPACE,togglespecialworkspace"
      "$mainMod SHIFT,1,movetoworkspace,1"
      "$mainMod SHIFT,2,movetoworkspace,2"
      "$mainMod SHIFT,3,movetoworkspace,3"
      "$mainMod SHIFT,4,movetoworkspace,4"
      "$mainMod SHIFT,5,movetoworkspace,5"
      "$mainMod SHIFT,6,movetoworkspace,6"
      "$mainMod SHIFT,7,movetoworkspace,7"
      "$mainMod SHIFT,8,movetoworkspace,8"
      "$mainMod SHIFT,9,movetoworkspace,9"
      "$mainMod SHIFT,0,movetoworkspace,10"
      "$mainMod CONTROL,right,workspace,e+1"
      "$mainMod CONTROL,left,workspace,e-1"
      "$mainMod,mouse_down,workspace, e+1"
      "$mainMod,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      "ALT,space,exec,global,caelestia:launcher"
      #----------AUDIO----------------------------------->>
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$mainMod, mouse:272, movewindow"
      "$mainMod, mouse:273, resizewindow"
    ];
  };
}
